apiVersion: v1
kind: ConfigMap
metadata:
    name: turing-fluentbit-cm
data:
    fluent-bit.conf: |-
        [SERVICE]
            Flush        1
            Daemon       Off
            Log_Level    info
            Parsers_File turing_parser.conf
            storage.path  /home/loco/logs/flb-storage/
            storage.backlog.mem_limit 10M
            storage.max_chunks_up 4
        [INPUT]
            Name tail
            Path /home/loco/logs/turing.log
            storage.type  filesystem
            Mem_Buf_Limit 1MB
            Buffer_Max_Size 10M
            Buffer_Chunk_Size 5M
            db request.db
            db.sync full
            Tag prod_api_logs_turing
            Skip_Long_Lines On      
        [FILTER]
            Name modify
            Match prod_api_logs_turing
            Add type prod_api_logs_turing
        [FILTER]
            Name modify
            Match prod_api_logs_turing
            Rename log message
            Add pod_name ${MY_POD_NAME}
            Add pod_name ${MY_POD_NAMESPACE}
            Add k8s.cluster.name prod-ivory
        [OUTPUT]
            Name redis
            Match *
            Hosts elk-redis.getloco.live
            DB 5
            key prod:turing
            Retry_Limit no_retries
            storage.total_limit_size 100M
    turing_parser.conf: |
        [PARSER]
            Name logfmt
            Format logfmt
            Time_Keep Off
            Time_Key time
            Time_Format %Y-%m-%dT%H:%M:%S.%L
