apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: turing-cpu
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clips-reco
  targetCPUUtilizationPercentage: 60
