version: 0.2

phases:
  pre_build:
    commands:
      # build tags
      - TAG="clips-reco.prod.$(date +%Y-%m-%d.%H.%M.%S)"
      - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:$TAG"'@' clips-reco/k8s/prod/deployment.yml

      # retrieve an authentication token and authenticate your docker client to ecr
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker login -u $dockerhub_username -p $dockerhub_password
    on-failure: ABORT

  build:
    commands:
      # Create a docker image
      - cd clips-reco && docker build -t clips-reco --build-arg aws_access_key=$TURING_AWS_ACCOUNT_ID --build-arg aws_access_secret=$TURING_AWS_SECRET_ACCESS_KEY -f k8s/Dockerfile .
    on-failure: ABORT

  post_build:
    commands:
      # push to ecr
      - docker tag clips-reco:latest $REPOSITORY_URI:$TAG
      - docker push $REPOSITORY_URI:$TAG

      # setup kubectl and apply
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - kubectl apply -f k8s/prod/fluentbit-config.yml
      - kubectl apply -f k8s/prod/deployment.yml
      - kubectl apply -f k8s/prod/hpa.yml
      - kubectl rollout restart deployment/clips-reco -n ivory
