apiVersion: v1
kind: Service
metadata:
  name: turing-api-svc
  namespace: turing-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:418915376963:certificate/ca96c082-d821-4dea-8f2c-80efb883ec1d
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    name: turing-api
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turing-api-dp
  namespace: turing-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      name: turing-api
  template:
    metadata:
      labels:
        name: turing-api
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: turing
      containers:
        - name: turing
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          env:
            - name: SERVICE_ROLE
              value: "API_SERVER"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 1G1
              cpu: 1000m
            limits:
              memory: 2Gi
              cpu: 1000m
          volumeMounts:
            - name: turing-log
              mountPath: /home/loco/logs/
        - name: fluentbit
          image: 418915376963.dkr.ecr.ap-south-1.amazonaws.com/redis-fluentbit:latest
          imagePullPolicy: Always
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WORKLOAD_NAME
              value: "prod_task"
            - name: ENVIRONMENT
              value: "prod"
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          volumeMounts:
            - name: turing-log
              mountPath: /home/loco/logs/
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: config
              mountPath: /fluent-bit/etc/turing_parser.conf
              subPath: turing_parser.conf
      volumes:
        - name: turing-log
          emptyDir: {}
        - name: config
          configMap:
            name: turing-fluentbit-cm
            defaultMode: 420
