apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: turing-api-dp-cpu
  namespace: turing-ns
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: turing-api-dp
  targetCPUUtilizationPercentage: 60
